import {
  readdirSync, statSync, readFileSync, existsSync, realpathSync,
  openSync, readSync, closeSync, accessSync, constants as fsConstants,
} from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import {
  Gitignore, extendedAt, repositoryExcludes, readGitIndex, isTracked, readBounded,
} from './gitignore.js';
import type { IndexLookup, TrackedPaths } from './gitignore.js';

/**
 * Directories that hold no first-party source: dependency trees, build output,
 * framework caches. Every name here has to be regenerable in *any* repository,
 * not just this one. `site/` and `_reference/` used to be on this list because
 * they are this project's own layout, which meant every user with a `site/`
 * directory had that whole subtree read as clean without being opened. A
 * scanner reporting clean on code it never read is its worst possible failure,
 * so nothing project-specific belongs here.
 */
const SKIP_DIRS = new Set([
  'node_modules', '.git', '.next', '.turbo', '.vercel', '.wrangler',
  'dist', 'build', 'out', 'coverage', '.venv', 'venv', '__pycache__',
  '.open-next', '.sst',
  '.cache', '.pnpm-store', 'vendor', 'target', '.svelte-kit', '.nuxt',
  '.cts-cache',
]);

const SCAN_EXTS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.mts', '.cts', '.sql',
  '.json', '.txt', '.toml', '.env', '.yaml', '.yml',
  // Prose files matter: AI agents copy `npm install <hallucination>` out of
  // READMEs and agent instruction files long before it reaches a manifest.
  '.md', '.mdc', '.mdx',
  // Reachable by the vendored community ruleset, which covers more ecosystems
  // than the AST scanners do.
  '.py', '.go', '.sh', '.bash', '.tf', '.tfvars', '.rb', '.php',
]);

/** Extensionless files worth reading. */
const NAMED_FILES = new Set(['Dockerfile', 'Makefile', 'Procfile']);

/** Instruction files read by coding agents. No extension, but high signal. */
const AGENT_FILES = new Set([
  '.cursorrules', '.windsurfrules', '.clinerules', '.aiderrules', '.goosehints',
]);

/** Files bigger than this are almost certainly bundles or fixtures, not source. */
export const MAX_FILE_BYTES = 2_000_000;

/**
 * Precise generated-code detection — deliberately NOT a blanket skip of any
 * `generated/` directory, which can legitimately hold hand-written code. Matches
 * the codegen outputs that produce false positives (a Prisma client ships its
 * own credentials, queryRawUnsafe and dynamic requires that are safe in vendor
 * code but read as findings), and files carrying a generated banner.
 */
const GENERATED_PATH =
  /(^|\/)(generated|__generated__)\/(prisma|graphql|gql|client)(\/|$)|(^|\/)\.prisma(\/|$)|\.(generated|gen)\.[cm]?[jt]sx?$/i;

const GENERATED_BANNER =
  /(^|\n).{0,4}(@generated\b|this (file|code) (is|was) (auto[- ]?)?generated|code generated by|do not edit|prisma client js|autogenerated)/i;

const BANNER_BYTES = 400;

function looksGenerated(fullPath: string): boolean {
  if (GENERATED_PATH.test(fullPath)) return true;
  // Cheap banner check on the first chunk for the ambiguous cases only. Read
  // that chunk rather than the file: a generated bundle is exactly the file
  // that is megabytes long, and only the first few hundred bytes are looked at.
  if (!/(^|\/)(generated|gen|__generated__|codegen)(\/|$)/i.test(fullPath)) return false;
  let fd: number | undefined;
  try {
    fd = openSync(fullPath, 'r');
    const buf = Buffer.alloc(BANNER_BYTES);
    const read = readSync(fd, buf, 0, BANNER_BYTES, 0);
    return GENERATED_BANNER.test(buf.subarray(0, read).toString('utf8'));
  } catch {
    return false;
  } finally {
    if (fd !== undefined) {
      try {
        closeSync(fd);
      } catch {
        /* already gone */
      }
    }
  }
}

export interface WalkResult {
  files: string[];
  /** How many paths were left out because the repository ignores them. */
  gitIgnored: number;
  /** How many symlinks pointed outside the scan root and were not followed. */
  escapingSymlinks: number;
  /** How many files were left unread for exceeding `MAX_FILE_BYTES`. */
  oversize: number;
  /** Names of the build/dependency directories skipped whole, deduplicated. */
  skippedDirs: string[];
  /**
   * Files the scan would have read and directories it would have entered, but
   * could not open (permission denied, mostly). Absolute paths. Every scanner
   * used to meet these as a `read()` that returned null and move on, so a
   * `chmod 000` file was counted as scanned and the run came out clear.
   */
  unreadable: string[];
  /** Things the walk wants said out loud, e.g. an index it could not read. */
  warnings: string[];
}

/**
 * Files a `.gitignore` excludes are still worth reading, because the tool
 * reasons about them by name: a secret in an ignored `.env` is on your disk
 * either way, and CTS032 exists to check that the file is ignored at all.
 */
const SCAN_EVEN_IF_IGNORED = /(^|\/)\.env(\.|$)/;

/** The repository whose index decides what is tracked beneath `root`. */
interface RepoContext {
  /** Working-tree root, in the walk's own path space (not realpath'd). */
  root: string;
  tracked: TrackedPaths;
}

/**
 * Finds the repository a walk starting at `start` belongs to, looking no higher
 * than `ceiling` (the project root): `cleartoship app` walks `app/`, but the
 * repository it is tracked by sits one level up.
 */
function findRepository(start: string, ceiling: string): { dir: string; lookup: IndexLookup } | null {
  let dir = resolve(start);
  const top = resolve(ceiling);
  const inside = dir === top || dir.startsWith(top.endsWith(sep) ? top : top + sep);
  for (;;) {
    const lookup = readGitIndex(dir);
    if (lookup.kind !== 'none') return { dir, lookup };
    if (!inside || dir === top) return null;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function relSlash(from: string, to: string): string {
  return relative(from, to).split(sep).join('/');
}

export function walk(
  root: string,
  options: { respectGitignore?: boolean; projectRoot?: string } = {},
): WalkResult {
  const found: string[] = [];
  const unreadable: string[] = [];
  const warnings: string[] = [];
  let gitIgnored = 0;

  // Git never ignores a file it tracks. Without this, a committed `.gitignore`
  // that lists a committed file hid that file from every scanner — reported
  // CLEAR TO SHIP on code nobody opened. So the index decides first, and when
  // there is a repository whose index cannot be read, ignore rules are not
  // honoured at all: scanning a few extra files is a cost, skipping a tracked
  // one is the failure this tool exists to prevent.
  let respect = options.respectGitignore !== false;
  let repo: RepoContext | null = null;
  if (respect) {
    const located = findRepository(root, options.projectRoot ?? root);
    if (located?.lookup.kind === 'ok') {
      repo = { root: located.dir, tracked: located.lookup.tracked };
    } else if (located?.lookup.kind === 'error') {
      respect = false;
      warnings.push(
        `${located.dir} is a git repository, but its index could not be read (${located.lookup.reason}), ` +
          'so which files git tracks is unknown. .gitignore was NOT honoured for this scan: ignored ' +
          'files were scanned too, rather than risk skipping a tracked one.',
      );
    }
  }

  // A symlink that leaves the tree is not part of the project, and following one
  // would be worse than useless: `vendor-config -> /home/runner/.ssh` makes the
  // scanner read that directory and quote what it finds — into a pull-request
  // comment, in the Action. So the scan stays inside what it was pointed at.
  let rootReal: string;
  try {
    rootReal = realpathSync(root);
  } catch {
    rootReal = root;
  }
  // Ignore files are read like everything else: inside the root, regular
  // files only, capped. `.gitignore -> /dev/zero` used to be read to the end.
  const readIgnore = (p: string) => readBounded(p, MAX_FILE_BYTES, rootReal);

  const rootRules = respect
    ? extendedAt(repositoryExcludes(root, readIgnore), root, readIgnore)
    : Gitignore.empty();

  interface Frame {
    dir: string;
    rules: Gitignore;
    /** Entered only because it holds tracked paths, though the rules ignore it. */
    ignoredButTracked: boolean;
  }
  const stack: Frame[] = [{ dir: root, rules: rootRules, ignoredButTracked: false }];
  // A symlinked directory that points back into the tree — `self -> .`, or the
  // A→B→A pair a workspace layout can produce — otherwise gets walked again on
  // every pass, reporting the same file at a dozen different paths. Resolving
  // each directory once and remembering it costs one syscall per directory.
  const visited = new Set<string>();
  let escapingSymlinks = 0;
  // What the walk chose not to read. Both are reported: a file skipped for its
  // size and a directory skipped by name produce no findings, and "no findings"
  // must never be silently indistinguishable from "nothing was wrong".
  let oversize = 0;
  const skippedDirs = new Set<string>();

  visited.add(rootReal);
  const insideRoot = (real: string): boolean =>
    real === rootReal || real.startsWith(rootReal.endsWith('/') ? rootReal : rootReal + '/');

  const tracked = (full: string, isDir: boolean): boolean => {
    if (!repo) return false;
    const r = relSlash(repo.root, full);
    if (r === '' || r.startsWith('..')) return false;
    return isTracked(repo.tracked, r, isDir);
  };

  /** Whether git would leave this path out: ignored by the rules and not tracked. */
  const ignored = (full: string, isDir: boolean, frame: Frame): boolean => {
    if (!respect) return false;
    if (tracked(full, isDir)) return false;
    // Inside a directory the rules ignore, only tracked paths belong to the project.
    if (frame.ignoredButTracked) return true;
    return frame.rules.ignores(full, isDir);
  };

  /** Whether one regular file is worth reading, and the tallies for when it is not. */
  const consider = (full: string, entry: string, size: number, frame: Frame): void => {
    if (!SCAN_EVEN_IF_IGNORED.test(full) && ignored(full, false, frame)) {
      gitIgnored++;
      return;
    }
    const dot = entry.lastIndexOf('.');
    const ext = dot === -1 ? '' : entry.slice(dot);
    // .env, .env.local, requirements.txt and friends have no useful extension.
    const scannable =
      SCAN_EXTS.has(ext) ||
      AGENT_FILES.has(entry) ||
      NAMED_FILES.has(entry) ||
      entry.startsWith('Dockerfile') ||
      entry.startsWith('.env') ||
      entry === 'requirements.txt';
    if (!scannable) return;
    // Counted only for files we would otherwise have read: a 5 MB image is not
    // a source file this skipped, and reporting it as one is noise.
    if (size > MAX_FILE_BYTES) {
      oversize++;
      return;
    }
    if (!canRead(full)) {
      unreadable.push(full);
      return;
    }
    if (!looksGenerated(full)) found.push(full);
  };

  // `cleartoship path/to/one/file.ts` names a file, which the CLI documents and
  // which the directory walk below cannot handle: `readdirSync` on a file
  // throws, the walk returns nothing, and the run reports CLEAR TO SHIP having
  // opened no files at all. So a file root is evaluated directly.
  let rootStat;
  try {
    rootStat = statSync(root);
  } catch {
    rootStat = null;
  }
  if (rootStat?.isFile()) {
    consider(root, root.slice(root.lastIndexOf(sep) + 1), rootStat.size, stack[0]!);
    return {
      files: found.sort(),
      gitIgnored,
      escapingSymlinks,
      oversize,
      skippedDirs: [],
      unreadable,
      warnings,
    };
  }

  while (stack.length) {
    const frame = stack.pop()!;
    const { dir, rules } = frame;
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      // A directory that exists but cannot be listed hides everything in it.
      // (A root that does not exist at all is reported by `scan` instead.)
      if (rootStat !== null) unreadable.push(dir);
      continue;
    }
    for (const entry of entries) {
      const full = join(dir, entry);
      let st;
      try {
        st = statSync(full);
      } catch {
        continue;
      }
      let real: string;
      try {
        real = realpathSync(full);
      } catch {
        continue;
      }
      if (!insideRoot(real)) {
        escapingSymlinks++;
        continue;
      }

      if (st.isDirectory()) {
        if (SKIP_DIRS.has(entry)) {
          skippedDirs.add(entry);
          continue;
        }
        if (visited.has(real)) continue;
        visited.add(real);
        // git never descends into an ignored directory, and neither do we —
        // which is also where most of the saving comes from. Unless git tracks
        // something inside it: then the walk goes in, and takes only the
        // tracked paths from it.
        let ignoredButTracked = frame.ignoredButTracked;
        if (respect) {
          const holdsTracked = tracked(full, true);
          const ruledOut = frame.ignoredButTracked || rules.ignores(full, true);
          if (ruledOut && !holdsTracked) {
            gitIgnored++;
            continue;
          }
          if (ruledOut) ignoredButTracked = true;
        }
        stack.push({
          dir: full,
          rules: respect ? extendedAt(rules, full, readIgnore) : rules,
          ignoredButTracked,
        });
        continue;
      }
      if (!st.isFile()) continue;
      consider(full, entry, st.size, frame);
    }
  }
  return {
    files: found.sort(),
    gitIgnored,
    escapingSymlinks,
    oversize,
    skippedDirs: [...skippedDirs].sort(),
    unreadable: unreadable.sort(),
    warnings,
  };
}

/** Whether this process can open the file for reading. */
function canRead(full: string): boolean {
  try {
    accessSync(full, fsConstants.R_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Reads one file the scan did not find by walking — a lockfile, `.npmrc`, the
 * root `package.json` — the way the walker reads everything else: `relPath`
 * must resolve (symlinks included) to a regular file inside `root`, no larger
 * than `maxBytes`. Anything else reads as absent.
 *
 * Every direct read of a fixed name goes through here. Before it, a
 * `pnpm-lock.yaml -> ../../somewhere/else` was read and its contents quoted in
 * the report, and a `.gitignore -> /dev/zero` was read until memory ran out.
 */
export function safeRead(root: string, relPath: string, maxBytes: number = MAX_FILE_BYTES): string | null {
  let rootReal: string;
  try {
    rootReal = realpathSync(root);
  } catch {
    return null;
  }
  return readBounded(isAbsolute(relPath) ? relPath : join(root, relPath), maxBytes, rootReal);
}

export function read(file: string): string | null {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return null;
  }
}

export function rel(root: string, file: string): string {
  const r = relative(root, file);
  return r === '' ? '.' : r.split(sep).join('/');
}

export function exists(p: string): boolean {
  return existsSync(p);
}

/** 1-indexed line number for a character offset. */
export function lineAt(source: string, index: number): number {
  let line = 1;
  for (let i = 0; i < index && i < source.length; i++) {
    if (source.charCodeAt(i) === 10) line++;
  }
  return line;
}

export function snippetAt(source: string, line: number): string {
  const text = source.split('\n')[line - 1] ?? '';
  const trimmed = text.trim();
  return trimmed.length > 160 ? trimmed.slice(0, 157) + '...' : trimmed;
}

const SCRIPT_EXTS = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.mts', '.cts']);

export function isScript(file: string): boolean {
  const dot = file.lastIndexOf('.');
  return dot !== -1 && SCRIPT_EXTS.has(file.slice(dot));
}

export function isSql(file: string): boolean {
  return file.endsWith('.sql');
}

/** Prose and agent-instruction files, where install commands get copy-pasted from. */
export function isProse(file: string): boolean {
  const base = file.slice(file.lastIndexOf('/') + 1);
  return /\.(md|mdc|mdx|txt)$/.test(base) || AGENT_FILES.has(base);
}

/** Language tokens the vendored community rules match on. */
export function languagesFor(file: string): string[] {
  const base = file.slice(file.lastIndexOf('/') + 1);
  const ext = base.includes('.') ? base.slice(base.lastIndexOf('.')) : '';
  if (base.startsWith('Dockerfile')) return ['dockerfile'];
  switch (ext) {
    case '.ts':
    case '.tsx':
    case '.mts':
    case '.cts':
      return ['typescript', 'javascript'];
    case '.js':
    case '.jsx':
    case '.mjs':
    case '.cjs':
      return ['javascript'];
    case '.json':
      return base === 'vercel.json' ? ['json', 'vercel-config'] : ['json'];
    case '.sql':
      return ['sql'];
    case '.yml':
    case '.yaml':
      return ['yaml'];
    case '.py':
      return ['python'];
    case '.go':
      return ['go'];
    case '.sh':
    case '.bash':
      return ['shell'];
    case '.tf':
    case '.tfvars':
      return ['terraform'];
    case '.rb':
      return ['ruby'];
    case '.php':
      return ['php'];
    default:
      return [];
  }
}
